2025-08-19 23:22:20.091537: W external/xla/xla/service/gpu/autotuning/dot_search_space.cc:200] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs?Working around this by using the full hints set instead.
2025-08-19 23:22:23.011605: W external/xla/xla/service/gpu/autotuning/dot_search_space.cc:200] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs?Working around this by using the full hints set instead.
2025-08-19 23:22:23.011658: W external/xla/xla/service/gpu/autotuning/dot_search_space.cc:200] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs?Working around this by using the full hints set instead.
2025-08-19 23:22:23.011669: W external/xla/xla/service/gpu/autotuning/dot_search_space.cc:200] All configs were filtered out because none of them sufficiently match the hints. Maybe the hints set does not contain a good representative set of valid configs?Working around this by using the full hints set instead.
Traceback (most recent call last):
  File "/p/project1/ehrtas/villalobos1/RiverSimCR/rainfall_analysis/DischargeForecastingDL/experiments.py", line 4, in <module>
    train_model()
  File "/p/project1/ehrtas/villalobos1/RiverSimCR/rainfall_analysis/DischargeForecastingDL/experiments/discharge_forecast.py", line 153, in train_model
    batch = shard_batch(batch)
  File "/p/project1/ehrtas/villalobos1/RiverSimCR/rainfall_analysis/DischargeForecastingDL/experiments/discharge_forecast.py", line 130, in shard_batch
    return jax.tree_util.tree_map(
  File "/p/project1/ehrtas/villalobos1/miniforge3/envs/OL/lib/python3.10/site-packages/jax/_src/tree_util.py", line 362, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/p/project1/ehrtas/villalobos1/miniforge3/envs/OL/lib/python3.10/site-packages/jax/_src/tree_util.py", line 362, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/p/project1/ehrtas/villalobos1/RiverSimCR/rainfall_analysis/DischargeForecastingDL/experiments/discharge_forecast.py", line 131, in <lambda>
    lambda x: x.reshape(jax.local_device_count(), -1, *x.shape[1:]),
  File "/p/project1/ehrtas/villalobos1/miniforge3/envs/OL/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 313, in _reshape
    newshape = _compute_newshape(self, args[0] if len(args) == 1 else args)
  File "/p/project1/ehrtas/villalobos1/miniforge3/envs/OL/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 464, in _compute_newshape
    raise TypeError(f"cannot reshape array of shape {arr.shape} (size {arr.size}) "
TypeError: cannot reshape array of shape (75, 128, 30) (size 288000) into shape (4, -1, 128, 30) because the product of specified axis sizes (15360) does not evenly divide 288000

ERROR conda.cli.main_run:execute(125): `conda run python experiments.py` failed. (See above for error)
[CudaDevice(id=0), CudaDevice(id=1), CudaDevice(id=2), CudaDevice(id=3)]

